# Generated by Django 5.2.8 on 2025-12-09 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OngAmp', '0007_alter_adocao_options_alter_adotante_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='is_adotado',
        ),
        migrations.AddField(
            model_name='pet',
            name='is_destaque',
            field=models.BooleanField(default=False, help_text='Marque se quiser que este pet apareça na página inicial.', verbose_name='Destaque na Home?'),
        ),
        migrations.AddField(
            model_name='pet',
            name='status_adocao',
            field=models.CharField(choices=[('DISPONIVEL', 'Disponível para Adoção'), ('EM_PROCESSO', 'Em Processo de Adoção'), ('ADOTADO', 'Adotado')], db_index=True, default='DISPONIVEL', max_length=20, verbose_name='Status de Adoção'),
        ),
    ]
