# Generated by Django 5.2.8 on 2025-12-15 20:38

import OngAmp.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OngAmp', '0008_remove_pet_is_adotado_pet_is_destaque_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentotransparencia',
            name='arquivo',
            field=models.FileField(upload_to='transparencia_pdfs/', validators=[OngAmp.validators.validar_pdf], verbose_name='Arquivo PDF'),
        ),
    ]
