# Generated by Django 5.2.8 on 2025-12-15 21:24

import OngAmp.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OngAmp', '0009_alter_documentotransparencia_arquivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentotransparencia',
            name='arquivo',
            field=models.FileField(help_text='Apenas arquivos .pdf são permitidos', upload_to='transparencia_pdfs/', validators=[OngAmp.validators.validar_pdf], verbose_name='Arquivo PDF'),
        ),
    ]
