# Generated by Django 5.2.8 on 2025-12-16 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OngAmp', '0010_alter_documentotransparencia_arquivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='raca',
            field=models.CharField(default='SRD', help_text="Ex: Labrador, Siamês, ou mantenha 'SRD' para Vira-lata.", max_length=50, verbose_name='Raça'),
        ),
    ]
