# Generated by Django 5.2.8 on 2026-01-05 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OngAmp', '0011_pet_raca'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoGeral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_recebimento', models.EmailField(default='ampa.mirassol@hotmail.com', help_text='Para onde devem ir os alertas de novos interessados?', max_length=254, verbose_name='E-mail que recebe as adoções')),
            ],
            options={
                'verbose_name': 'Configuração do Site',
                'verbose_name_plural': 'Configurações do Site',
            },
        ),
    ]
